In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df=pd.read_csv("bank.csv")
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,33,blue-collar,single,primary,no,1,yes,no,cellular,20,apr,257,1,-1,0,unknown,no
11158,39,services,married,secondary,no,733,no,no,unknown,16,jun,83,4,-1,0,unknown,no
11159,32,technician,single,secondary,no,29,no,no,cellular,19,aug,156,2,-1,0,unknown,no
11160,43,technician,married,secondary,no,0,no,yes,cellular,8,may,9,2,172,5,failure,no
11161,34,technician,married,secondary,no,0,no,no,cellular,9,jul,628,1,-1,0,unknown,no

In [3]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for col in df.columns[[1,2,3,4,6,7,8,10,15,16]]:
    df[col]=le.fit_transform(df[col])
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,0,1,1,0,2343,1,0,2,5,8,1042,1,-1,0,3,1
1,56,0,1,1,0,45,0,0,2,5,8,1467,1,-1,0,3,1
2,41,9,1,1,0,1270,1,0,2,5,8,1389,1,-1,0,3,1
3,55,7,1,1,0,2476,1,0,2,5,8,579,1,-1,0,3,1
4,54,0,1,2,0,184,0,0,2,5,8,673,2,-1,0,3,1

In [4]:
print(df['deposit'].value_counts())

deposit
0    5873
1    5289
Name: count, dtype: int64

In [5]:
#DECISION TREE
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,f1_score,precision_score,recall_score
from sklearn.model_selection import train_test_split

X=df.drop("deposit",axis=1)
y=df["deposit"]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

model = DecisionTreeClassifier( max_depth=5,
    random_state=42)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

test_score=model.score(X_test,y_test)
train_score=model.score(X_train,y_train)

accuracy=accuracy_score(y_test,y_pred)
f1=f1_score(y_test,y_pred)
recall=recall_score(y_test,y_pred)
precision=precision_score(y_test,y_pred)

print("train_score:", train_score)
print("test_score:",test_score)
print("accuracy_score:",accuracy)
print("f1_score:",f1)
print("precision_score:",precision)
print("recall_score:",recall)

train_score: 0.8147958530654038
test_score: 0.8044192296207823
accuracy_score: 0.8044192296207823
f1_score: 0.7983995075407818
precision_score: 0.7898903775883069
recall_score: 0.8070939639079029

In [6]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler

X = df.drop("deposit", axis=1)
y = df["deposit"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = DecisionTreeClassifier()

param_grid = {
    'max_depth': [8, 10, 12],
    'min_samples_split': [4, 5, 6],
    'min_samples_leaf': [2, 4, 5]
}

gridsearch = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

gridsearch.fit(X_train, y_train)

print("Best Parameters:", gridsearch.best_params_)
print("Best CV Score:", gridsearch.best_score_)

hello = gridsearch.best_estimator_
y_pred = hello.predict(X_test)

train_score = hello.score(X_train, y_train)
test_score = hello.score(X_test, y_test)

accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)

print("-" * 30)
print("train_score:", train_score)
print("test_score:", test_score)
print("accuracy_score:", accuracy)
print("f1_score:", f1)
print("precision_score:", precision)
print("recall_score:", recall)

Best Parameters: {'max_depth': 8, 'min_samples_leaf': 2, 'min_samples_split': 4}
Best CV Score: 0.8092919407914948
------------------------------
train_score: 0.8499936004095738
test_score: 0.8112869513287548
accuracy_score: 0.8112869513287548
f1_score: 0.8005050505050505
precision_score: 0.8122998078155029
recall_score: 0.7890479153702551

In [7]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score,precision_score,recall_score
from sklearn.model_selection import train_test_split


X=df.drop('deposit', axis=1)
y=df['deposit']

X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.3, random_state=42)

model=RandomForestClassifier(n_estimators=200, max_depth=5,
    random_state=42)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

train_score=model.score(X_train,y_train)
test_score=model.score(X_test,y_test)

accuracy=accuracy_score(y_test,y_pred)
f1=f1_score(y_test,y_pred)
precision=precision_score(y_test,y_pred)
recall=recall_score(y_test,y_pred)

print("train_score:", train_score)
print("test_score:",test_score)
print("accuracy_score:",accuracy)
print("f1_score:",f1)
print("precision_score:",precision)
print("recall_score:",recall)

train_score: 0.8234992960450531
test_score: 0.8091967751567632
accuracy_score: 0.8091967751567632
f1_score: 0.8030816640986133
precision_score: 0.7954822954822954
recall_score: 0.8108276291225887

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

X = df.drop('deposit', axis=1)
y = df['deposit']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42
)

rf = RandomForestClassifier(random_state=42)

param_grid = {
    'n_estimators': [200, 300],
    'max_depth': [8, 10, 12],
    'min_samples_split': [5, 10, 15],
    'min_samples_leaf': [2, 4, 6]
}

grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)
grid_search.fit(X_train, y_train)

print("Best Parameters:", grid_search.best_params_)
print("Best CV Score:", grid_search.best_score_)

best_model = grid_search.best_estimator_

y_pred = best_model.predict(X_test)

train_score = best_model.score(X_train, y_train)
test_score = best_model.score(X_test, y_test)

print("Train Score:", train_score)
print("Test Score :", test_score)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))

Best Parameters: {'max_depth': 12, 'min_samples_leaf': 2, 'min_samples_split': 10, 'n_estimators': 200}
Best CV Score: 0.8430836984917708
Train Score: 0.9010623320107514
Test Score : 0.8342788892206628
Accuracy: 0.8342788892206628
F1 Score: 0.8327809581199156
Precision: 0.8072429906542056
Recall: 0.8599875544492844

In [9]:
###BAGGOING CLASSIFIER
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

X = df.drop('deposit', axis=1)
y = df['deposit']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42)
model = BaggingClassifier(
    estimator=DecisionTreeClassifier(max_depth=5),
    n_estimators=100,
    random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)

accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print("Train Score:", train_score)
print("Test Score:", test_score)
print("Accuracy Score:", accuracy)
print("F1 Score:", f1)
print("Precision Score:", precision)
print("Recall Score:", recall)

Train Score: 0.8226033533853834
Test Score: 0.8151687070767393
Accuracy Score: 0.8151687070767393
F1 Score: 0.8097141100522595
Precision Score: 0.8001215066828675
Recall Score: 0.819539514623522

In [10]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

# Features and target
X = df.drop('deposit', axis=1)
y = df['deposit']

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42)

bag = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    random_state=42)

param_grid = {
    'n_estimators': [50, 100, 200],
    'estimator__max_depth': [3, 5, 10]
}

grid = GridSearchCV(
    estimator=bag,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1)


grid.fit(X_train, y_train)

train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)


model = grid.best_estimator_


y_pred = model.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print("Train Score:", train_score)
print("Test Score:", test_score)
print("Best Parameters:", grid.best_params_)
print("Accuracy:", accuracy)
print("F1 Score:", f1)
print("Precision:", precision)
print("Recall:", recall)

Train Score: 0.8226033533853834
Test Score: 0.8151687070767393
Best Parameters: {'estimator__max_depth': 10, 'n_estimators': 200}
Accuracy: 0.8384592415646461
F1 Score: 0.8367038937518865
Precision: 0.8124267291910903
Recall: 0.8624766645924082

In [11]:
##ADABOOST

from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score,precision_score,recall_score

X = df.drop('deposit', axis=1)
y = df['deposit']

X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.3, random_state=42)

model=AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=5),
    random_state=42,
    learning_rate=1.0,
    n_estimators=100
)

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

test_score=model.score(X_test,y_test)
train_score=model.score(X_train,y_train)

accuracy=accuracy_score(y_test,y_pred)
f1=f1_score(y_test,y_pred)
precision=precision_score(y_test,y_pred)
recall=recall_score(y_test,y_pred)

print("test_score:",test_score)
print("train_score:",train_score)
print("accuracy_score:",accuracy)
print("f1_score:",f1)
print("recall_score:",recall)
print("precision_score:",precision)

test_score: 0.8384592415646461
train_score: 0.9045181108409062
accuracy_score: 0.8384592415646461
f1_score: 0.8336919766369505
recall_score: 0.8438083385189795
precision_score: 0.8238153098420413

In [12]:
##ADABOOST gridsearch cv

from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, f1_score,precision_score,recall_score

X = df.drop('deposit', axis=1)
y = df['deposit']

X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.3, random_state=42)

model=AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=3),
    random_state=42,
    learning_rate=1.0,
    n_estimators=50
)

param_grid={
    'n_estimators':[100,200,250],
    'learning_rate':[0.01,0.1,1,2,10]
}

gridsearch=GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    scoring='accuracy',
    n_jobs=-1)



gridsearch.fit(X_train,y_train)

print("Best Parameters:", gridsearch.best_params_)
print("Best CV Score:", gridsearch.best_score_)

best_model=gridsearch.best_estimator_

y_pred=best_model.predict(X_test)

test_score=best_model.score(X_test,y_test)
train_score=best_model.score(X_train,y_train)

accuracy=accuracy_score(y_test,y_pred)
f1=f1_score(y_test,y_pred)
precision=precision_score(y_test,y_pred)
recall=recall_score(y_test,y_pred)

print("test_score:",test_score)
print("train_score:",train_score)
print("accuracy_score:",accuracy)
print("f1_score:",f1)
print("recall_score:",recall)
print("precision_score:",precision)

Best Parameters: {'learning_rate': 1, 'n_estimators': 250}
Best CV Score: 0.8462817736992537
test_score: 0.8393550313526426
train_score: 0.8607449123256111
accuracy_score: 0.8393550313526426
f1_score: 0.8362751065124772
recall_score: 0.8550093341630367
precision_score: 0.8183442525312686

In [13]:
## GRADIENT BOOSTING 


from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score,precision_score,recall_score

X = df.drop('deposit', axis=1)
y = df['deposit']

X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.3, random_state=42)

model= GradientBoostingClassifier(
    n_estimators=50,
    random_state=42,
    learning_rate=0.2,
    max_depth=2
)

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

test_score=model.score(X_test,y_test)
train_score=model.score(X_train,y_train)

accuracy=accuracy_score(y_test,y_pred)
f1=f1_score(y_test,y_pred)
precision=precision_score(y_test,y_pred)
recall=recall_score(y_test,y_pred)

print("test_score:",test_score)
print("train_score:",train_score)
print("accuracy_score:",accuracy)
print("f1_score:",f1)
print("recall_score:",recall)
print("precision_score:",precision)

test_score: 0.8223350253807107
train_score: 0.8364264687060028
accuracy_score: 0.8223350253807107
f1_score: 0.8170919151552413
recall_score: 0.8270068450528936
precision_score: 0.807411907654921

In [14]:
## GRADIENT BOOSTING  GRIDSEARCH


from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import accuracy_score, f1_score,precision_score,recall_score

X = df.drop('deposit', axis=1)
y = df['deposit']

X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.3, random_state=42)

model= GradientBoostingClassifier(
    random_state=42,
)


param_grid={
    'n_estimators': [50, 100, 150],
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': [1, 2, 3],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

gridsearch=GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    n_jobs=-1,
    cv=5,
    scoring='accuracy')


gridsearch.fit(X_train,y_train)

print("Best Parameters:", gridsearch.best_params_)
print("Best CV Score:", gridsearch.best_score_)

best_model=gridsearch.best_estimator_

y_pred=best_model.predict(X_test)

test_score=best_model.score(X_test,y_test)
train_score=best_model.score(X_train,y_train)

accuracy=accuracy_score(y_test,y_pred)
f1=f1_score(y_test,y_pred)
precision=precision_score(y_test,y_pred)
recall=recall_score(y_test,y_pred)

print("test_score:",test_score)
print("train_score:",train_score)
print("accuracy_score:",accuracy)
print("f1_score:",f1)
print("recall_score:",recall)
print("precision_score:",precision)

Best Parameters: {'learning_rate': 0.1, 'max_depth': 3, 'min_samples_leaf': 4, 'min_samples_split': 2, 'n_estimators': 150}
Best CV Score: 0.8503780198787092
test_score: 0.8393550313526426
train_score: 0.8666325355177269
accuracy_score: 0.8393550313526426
f1_score: 0.8367718446601942
recall_score: 0.8581207218419415
precision_score: 0.8164594434576673

In [15]:
## XGBOOST classifier


from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score,precision_score,recall_score

X = df.drop('deposit', axis=1)
y = df['deposit']

X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.3, random_state=42)

model= XGBClassifier(
    n_estimators=50,
    random_state=42,
    learning_rate=0.1,
    max_depth=2
)

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

test_score=model.score(X_test,y_test)
train_score=model.score(X_train,y_train)

accuracy=accuracy_score(y_test,y_pred)
f1=f1_score(y_test,y_pred)
precision=precision_score(y_test,y_pred)
recall=recall_score(y_test,y_pred)

print("test_score:",test_score)
print("train_score:",train_score)
print("accuracy_score:",accuracy)
print("f1_score:",f1)
print("recall_score:",recall)
print("precision_score:",precision)

test_score: 0.8145715138847417
train_score: 0.825931140407014
accuracy_score: 0.8145715138847417
f1_score: 0.810149801284011
recall_score: 0.8245177349097698
precision_score: 0.7962740384615384

In [16]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score


X = df.drop('deposit', axis=1)
y = df['deposit']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42
)

model = XGBClassifier(
    random_state=42
)

param_grid = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 5, 7],
    'min_child_weight': [1, 3, 5]
}

gridsearch = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

gridsearch.fit(X_train, y_train)

best_model = gridsearch.best_estimator_

y_pred = best_model.predict(X_test)

train_score = best_model.score(X_train, y_train)
test_score = best_model.score(X_test, y_test)

accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print("Best Parameters:", gridsearch.best_params_)
print("Train Score:", train_score)
print("Test Score:", test_score)
print("Accuracy:", accuracy)
print("F1 Score:", f1)
print("Precision:", precision)
print("Recall:", recall)

Best Parameters: {'learning_rate': 0.1, 'max_depth': 7, 'min_child_weight': 1, 'n_estimators': 200}
Train Score: 0.9618584410597721
Test Score: 0.8551806509405793
Accuracy: 0.8551806509405793
F1 Score: 0.8519987793713762
Precision: 0.8359281437125748
Recall: 0.8686994399502178

In [17]:
pip install lightgbm

Requirement already satisfied: lightgbm in c:\users\dell\anaconda3\lib\site-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in c:\users\dell\anaconda3\lib\site-packages (from lightgbm) (2.3.5)
Requirement already satisfied: scipy in c:\users\dell\anaconda3\lib\site-packages (from lightgbm) (1.16.3)
Note: you may need to restart the kernel to use updated packages.

In [18]:
from lightgbm import LGBMClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score,precision_score,recall_score

X = df.drop('deposit', axis=1)
y = df['deposit']

X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.3, random_state=42)

model= LGBMClassifier(
    n_estimators=50,
    random_state=42,
    learning_rate=0.1,
    max_depth=2
)

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

test_score=model.score(X_test,y_test)
train_score=model.score(X_train,y_train)

accuracy=accuracy_score(y_test,y_pred)
f1=f1_score(y_test,y_pred)
precision=precision_score(y_test,y_pred)
recall=recall_score(y_test,y_pred)

print("test_score:",test_score)
print("train_score:",train_score)
print("accuracy_score:",accuracy)
print("f1_score:",f1)
print("recall_score:",recall)
print("precision_score:",precision)

[LightGBM] [Info] Number of positive: 3682, number of negative: 4131
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002975 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 963
[LightGBM] [Info] Number of data points in the train set: 7813, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.471266 -> initscore=-0.115063
[LightGBM] [Info] Start training from score -0.115063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
test_score: 0.8136757240967453
train_score: 0.8236272878535774
accuracy_score: 0.8136757240967453
f1_score: 0.8099878197320342
recall_score: 0.8276291225886746
precision_score: 0.793082886106142

In [19]:
from lightgbm import LGBMClassifier
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import accuracy_score,f1_score,recall_score,precision_score

X=df.drop("deposit",axis=1)
y=df["deposit"]

X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.3,random_state=42)

param_grid={
    'n_estimators':[100,200,300],
    'learning_rate':[0.01,0.2,0.3],
    'max_depth':[2,4,5],
    'num_leaves':[23,45,76]
}

gridsearch=GridSearchCV(
    estimator=LGBMClassifier(random_state=42),
    param_grid=param_grid,
    scoring='accuracy',
    n_jobs=-1,
    cv=3
)

gridsearch.fit(X_train,y_train)

print("Best Parameters:", gridsearch.best_params_)
print("Best CV Score:", gridsearch.best_score_)

best_model=gridsearch.best_estimator_

y_pred=best_model.predict(X_test)



accuracy=accuracy_score(y_test,y_pred)
f1 = f1_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print("Best Parameters:", gridsearch.best_params_)
print("Train Score:", train_score)
print("Test Score:", test_score)
print("Accuracy:", accuracy)
print("F1 Score:", f1)
print("Precision:", precision)
print("Recall:", recall)

[LightGBM] [Info] Number of positive: 3682, number of negative: 4131
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001558 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 963
[LightGBM] [Info] Number of data points in the train set: 7813, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.471266 -> initscore=-0.115063
[LightGBM] [Info] Start training from score -0.115063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Best Parameters: {'learning_rate': 0.2, 'max_depth': 5, 'n_estimators': 100, 'num_leaves': 23}
Best CV Score: 0.8539618167040617
Best Parameters: {'learning_rate': 0.2, 'max_depth': 5, 'n_estimators': 100, 'num_leaves': 23}
Train Score: 0.8236272878535774
Test Score: 0.8136757240967453
Accuracy: 0.8533890713645864
F1 Score: 0.8498929990828493
Precision: 0.8353365384615384
Recall: 0.864965774735532

In [20]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score


X = df.drop('deposit', axis=1)
y = df['deposit']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42
)

model = XGBClassifier(
    random_state=42
)

param_grid = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.02,0.05],
    'max_depth': [3, 5, 7],
    'min_child_weight': [1, 3, 5]
}

gridsearch = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

gridsearch.fit(X_train, y_train)

best_model = gridsearch.best_estimator_

y_pred = best_model.predict(X_test)

train_score = best_model.score(X_train, y_train)
test_score = best_model.score(X_test, y_test)

accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print("Best Parameters:", gridsearch.best_params_)
print("Train Score:", train_score)
print("Test Score:", test_score)
print("Accuracy:", accuracy)
print("F1 Score:", f1)
print("Precision:", precision)
print("Recall:", recall)

Best Parameters: {'learning_rate': 0.05, 'max_depth': 7, 'min_child_weight': 5, 'n_estimators': 200}
Train Score: 0.9093817995648279
Test Score: 0.8498059122126008
Accuracy: 0.8498059122126008
F1 Score: 0.8472517461281506
Precision: 0.8274021352313167
Recall: 0.8680771624144369